sudo: required
services:
  - docker


before_install:
  - docker build -t hracho/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hracho/docker-react npm run test


deploy:
   provider: elasticbeanstalk
   region:  "eu-central-1"
   app: "docker-react"
   env: "DockerReact-env"
   bucket_name: "elasticbeanstalk-eu-central-1-900873517060"
   bucket_path: "docker-react"
   on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"